# -*- coding: utf-8 -*-
from termcolor import colored
import os
import menu
import requests
import time
import json
def clear():
	if os.name == 'nt':
  		os.system('cls')
  		print('!! WARNING !!')
  		print('Dont use windows lmao')
	else:
		os.system('clear')
def barra():
	print('====================================')
def scan11():
	ip = input(colored('Insira o ip que quer scanear > ','cyan'))
	barra()
	verb = input(colored('Quer verbose? [S/n] > ','cyan'))
	if verb == 'S' or verb == 's':
		print(colored('[+] Verbose','green'))
		print(colored(f'[+] Alvo : {ip} ','green'))
		print(colored('[+] A começar!','green'))
		output = os.system(f'nmap -o -v {ip}')
		barra()
	elif verb == 'N' or verb =='n':
		print(colored('[+] Verbose','green'))
		print(colored(f'[+] Alvo : {ip} ','green'))
		print(colored('[+] A começar!','green'))
		output = os.system(f'nmap -o {ip}')
		barra()
	fchr = input(colored('[?] Deseja criar um ficheiro do resultado? [S/n] > ','yellow'))
	if fchr == 'S' or fchr == 's':
		nome = input(colored('[?] Quer salvar o ficheiro com que nome > ','cyan'))
		print(colored('[+] A criar um ficheiro do resultado (pode levar um bocado)...','cyan'))
		f = open(nome,'w+')
		f.write(str(os.system(f'nmap -A {ip} > {nome}')))
		print (colored('[+] O ficheiro foi criado na mesma pasta do programa!','cyan'))
		time.sleep(1)
		barra()
		print(colored('~ Bye ^^','cyan'))
		print(colored('github.com/iTremix','blue'))
		exit()
	else:
		barra()
		print(colored('~ Bye ^^','cyan'))
		print(colored('github.com/iTremix', 'red', attrs=['blink']))
		exit()

def scan22():
	ip = input(colored('Insira o ip que quer scanear > ','cyan'))
	barra()
	verb = input(colored('Quer verbose? [S/n] > ','cyan'))
	if verb == 'S' or verb == 's':
		print(colored('[+] Verbose','green'))
		print(colored(f'[+] Alvo : {ip} ','green'))
		print(colored('[+] A começar!','green'))
		output = os.system(f'nmap -v {ip}')
		barra()
	elif verb == 'N' or verb =='n':
		print(colored('[+] Verbose','green'))
		print(colored(f'[+] Alvo : {ip} ','green'))
		print(colored('[+] A começar!','green'))
		output = os.system(f'nmap {ip}')
		barra()
	fchr = input(colored('[?] Deseja criar um ficheiro do resultado? [S/n] > ','yellow'))
	if fchr == 'S' or fchr == 's':
		nome = input(colored('[?] Quer salvar o ficheiro com que nome > ','cyan'))
		print(colored('[+] A criar um ficheiro do resultado (pode levar um bocado)...','cyan'))
		f = open(nome,'w+')
		f.write(str(os.system(f'nmap -A {ip} > {nome}')))
		print (colored('[+] O ficheiro foi criado na mesma pasta do programa!','cyan'))
		time.sleep(1)
		barra()
		print(colored('~ Bye ^^','cyan'))
		print(colored('github.com/iTremix','blue'))
		exit()
	else:
		barra()
		print(colored('~ Bye ^^','cyan'))
		print(colored('github.com/iTremix', 'red', attrs=['blink']))
		exit()
def scan33():
	ip = input(colored('Insira o ip que quer scanear > ','cyan'))
	barra()
	verb = input(colored('Quer verbose? [S/n] > ','cyan'))
	if verb == 'S' or verb == 's':
		print(colored('[+] Verbose','green'))
		print(colored(f'[+] Alvo : {ip} ','green'))
		print(colored('[+] A começar!','green'))
		output = os.system(f'nmap -A -Pn -v {ip}')
		barra()
	elif verb == 'N' or verb =='n':
		print(colored('[+] Verbose','green'))
		print(colored(f'[+] Alvo : {ip} ','green'))
		print(colored('[+] A começar!','green'))
		output = os.system(f'nmap -A -Pn {ip}')
		barra()
	fchr = input(colored('[?] Deseja criar um ficheiro do resultado? [S/n] > ','yellow'))
	if fchr == 'S' or fchr == 's':
		nome = input(colored('[?] Quer salvar o ficheiro com que nome > ','cyan'))
		print(colored('[+] A criar um ficheiro do resultado (pode levar um bocado)...','cyan'))
		f = open(nome,'w+')
		f.write(str(os.system(f'nmap -A {ip} > {nome}')))
		print (colored('[+] O ficheiro foi criado na mesma pasta do programa!','cyan'))
		time.sleep(1)
		barra()
		print(colored('~ Bye ^^','cyan'))
		print(colored('github.com/iTremix','blue'))
		exit()
	else:
		barra()
		print(colored('~ Bye ^^','cyan'))
		print(colored('github.com/iTremix', 'red', attrs=['blink']))
		exit()
def scan44():
	ip = input(colored('Insira o ip que quer scanear > ','cyan'))
	barra()
	verb = input(colored('Quer verbose? [S/n] > ','cyan'))
	if verb == 'S' or verb == 's':
		print(colored('[+] Verbose','green'))
		print(colored(f'[+] Alvo : {ip} ','green'))
		print(colored('[+] A começar!','green'))
		output = os.system(f'nmap -sU -v{ip}')
		barra()
	elif verb == 'N' or verb =='n':
		print(colored('[+] Verbose','green'))
		print(colored(f'[+] Alvo : {ip} ','green'))
		print(colored('[+] A começar!','green'))
		output = os.system(f'nmap -sU {ip}')
		barra()
	fchr = input(colored('[?] Deseja criar um ficheiro do resultado? [S/n] > ','yellow'))
	if fchr == 'S' or fchr == 's':
		nome = input(colored('[?] Quer salvar o ficheiro com que nome > ','cyan'))
		print(colored('[+] A criar um ficheiro do resultado (pode levar um bocado)...','cyan'))
		f = open(nome,'w+')
		f.write(str(os.system(f'nmap -A {ip} > {nome}')))
		print (colored('[+] O ficheiro foi criado na mesma pasta do programa!','cyan'))
		time.sleep(1)
		barra()
		print(colored('~ Bye ^^','cyan'))
		print(colored('github.com/iTremix','blue'))
		exit()
	else:
		barra()
		print(colored('~ Bye ^^','cyan'))
		print(colored('github.com/iTremix', 'red', attrs=['blink']))
		exit()
def scan55():
	ip = input(colored('Insira o ip que quer scanear > ','cyan'))
	barra()
	verb = input(colored('Quer verbose? [S/n] > ','cyan'))
	if verb == 'S' or verb == 's':
		print(colored('[+] Verbose','green'))
		print(colored(f'[+] Alvo : {ip} ','green'))
		print(colored('[+] A começar!','green'))
		output = os.system(f'nmap -sT -v {ip}')
		barra()
	elif verb == 'N' or verb =='n':
		print(colored('[+] Verbose','green'))
		print(colored(f'[+] Alvo : {ip} ','green'))
		print(colored('[+] A começar!','green'))
		output = os.system(f'nmap -sT {ip}')
		barra()
	fchr = input(colored('[?] Deseja criar um ficheiro do resultado? [S/n] > ','yellow'))
	if fchr == 'S' or fchr == 's':
		nome = input(colored('[?] Quer salvar o ficheiro com que nome > ','cyan'))
		print(colored('[+] A criar um ficheiro do resultado (pode levar um bocado)...','cyan'))
		f = open(nome,'w+')
		f.write(str(os.system(f'nmap -A {ip} > {nome}')))
		print (colored('[+] O ficheiro foi criado na mesma pasta do programa!','cyan'))
		time.sleep(1)
		barra()
		print(colored('~ Bye ^^','cyan'))
		print(colored('github.com/iTremix','blue'))
		exit()
	else:
		barra()
		print(colored('~ Bye ^^','cyan'))
		print(colored('github.com/iTremix', 'red', attrs=['blink']))
		exit()
def scan66():
	ip = input(colored('Insira o ip que quer scanear > ','cyan'))
	barra()
	verb = input(colored('Quer verbose? [S/n] > ','cyan'))
	if verb == 'S' or verb == 's':
		print(colored('[+] Verbose','green'))
		print(colored(f'[+] Alvo : {ip} ','green'))
		print(colored('[+] A começar!','green'))
		output = os.system(f'nmap -sL -v {ip}')
		barra()
	elif verb == 'N' or verb =='n':
		print(colored('[+] Verbose','green'))
		print(colored(f'[+] Alvo : {ip} ','green'))
		print(colored('[+] A começar!','green'))
		output = os.system(f'nmap -sL {ip}')
		barra()
	fchr = input(colored('[?] Deseja criar um ficheiro do resultado? [S/n] > ','yellow'))
	if fchr == 'S' or fchr == 's':
		nome = input(colored('[?] Quer salvar o ficheiro com que nome > ','cyan'))
		print(colored('[+] A criar um ficheiro do resultado (pode levar um bocado)...','cyan'))
		f = open(nome,'w+')
		f.write(str(os.system(f'nmap -A {ip} > {nome}')))
		print (colored('[+] O ficheiro foi criado na mesma pasta do programa!','cyan'))
		time.sleep(1)
		barra()
		print(colored('~ Bye ^^','cyan'))
		print(colored('github.com/iTremix','blue'))
		exit()
	else:
		barra()
		print(colored('~ Bye ^^','cyan'))
		print(colored('github.com/iTremix', 'red', attrs=['blink']))
		exit()
def scan77():
	ip = input(colored('Insira o ip que quer scanear > ','cyan'))
	barra()
	req = requests.get('http://ip-api.com/json/'+ip)
	p = json.dumps(req.json(), indent=2)
	print(p)
	time.sleep(5)
	barra()
	print(colored('~ Bye ^^','cyan'))
	print(colored('github.com/iTremix', 'red', attrs=['blink']))
	exit()